config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "users#index"
  unauthenticated :user do
    root 'splash#index', as: :unauthenticated_root
  end

  authenticated :user do
    root 'categories#index', as: :authenticated_root
  end
  devise_for :users
  resources :users
  resources :categories, only: [:index, :new, :create] do
    resources :products, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_products
  has_many :products, through: :category_products

  has_one_attached :image
end

app/models/category_product.rb
class CategoryProduct < ApplicationRecord
  belongs_to :category
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  has_many :category_products, dependent: :destroy
  has_many :categories, through: :category_products

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, :set_user
  def set_user
    @user = current_user
  end

  def index
    @categories = @user.categories
  end

  def new
    @user = current_user
    @category = @user.categories.build
  end

  def create
    @user = current_user
    @category = @user.categories.build(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Category created successfully.'
    else
      render :new
    end
  end

  def category_params
    params.require(:category).permit(:name, :image)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_category
  def set_category
    @user = current_user
    @category = @user.categories.find(params[:category_id])
  end

  def new
    @product = @category.products.build
  end

  def create
    @product = @category.products.build(product_params)
    @product.user_id = current_user.id
    @product.category_id = @category.id

    if @product.save
      redirect_to category_products_path(@category), notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  def product_params
    params.require(:product).permit(:name, :amount)
  end

  def index
    @products = Product.where(category_id: @category.id).order(created_at: :desc)
    @category_name = @category.name
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def category_products_sum(id)
    Product.where(category_id: id).sum(:amount)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<!-- app/views/categories/index.html.erb -->
<%= render partial: 'shared/nav', locals: { h1_content: "Categories" } %>

<section class='all_categories'>
  <% if @categories.empty? %>
    <h2>Add new category</h2>
  <%end%>
  <% @categories.each do |category| %>
    <%= link_to category_products_path(category.id) do %>
      <div class="category">
        <div class='cat_img_details'>
          <div class='img_div'>
            <%= image_tag category.image %>
          </div>
          <div class='cat_details'>
            <h2 class='cat-name'><%= category.name.capitalize %></h2>
            <p class='cat_created'><%= category.created_at.strftime("%e, %b %Y") %></p>     
          </div>
        </div>  
        <p class='cat-amount'>$ <%= category_products_sum(category.id) %> </p>
      </div>
   <%end%>
  <% end %>

</section>

<div class='btn_ctn'>
      <button class='add_cat'>
            <%= link_to "Add new category", new_category_path %>
     </button>
</div>

app/views/categories/new.html.erb
<!-- app/views/categories/new.html.erb -->
<%= render partial: 'shared/nav', locals: { h1_content: "Categories" } %>
<button class='cat_back'>
  <%= link_to "Back", categories_path %>
</button>

<section class='cat_form'>
  <%= form_with model: @category, url: categories_path, multipart: true do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>

  <div class="field">
    <%= form.label :icon %>
    <%= form.file_field :image, required: true %>
  </div>

  <div class="actions">
    <%= form.submit "Create Category" %>
  </div>
<% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/products/index.html.erb
<%= render partial: 'shared/nav', locals: { h1_content: "Transactions" } %>

<div class='pro_cat'>
  <h2>
    <%= @category_name%>  
  </h2>
  <p class='cat-amount'>
   $ <%= @products.sum(:amount)%>
  </p>
</div>

<% @products.each do |product| %>
     <div class="each_product">
      <p><%= product.name.capitalize %></p>
      <p>$ <%= product.amount %> (<%= product.created_at.strftime("%e, %b %Y") %>)</p>
    </div>
<% end %>

<button class='cat_back'>
  <%= link_to "Back", categories_path %>
</button>

<div class='btn_ctn'>
    <button class='add_cat'> 
      <%= link_to "Add transactions", new_category_product_path %>
    </button>
</div>

app/views/products/new.html.erb
<%= render partial: 'shared/nav', locals: { h1_content: "New Transactions" } %>
<button class='cat_back'>
  <%= link_to "Back", category_products_path(@category) %>
</button>


<section class='cat_form'>
  <%= form_with model: @product, url: category_products_path(@category), local: true, class: "form" do |f|%>
    
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount, required: true %>
  </div>

      <div class="form-group">
      <%= f.label :categories, "Select Category/ Categories" %>
      <%= f.collection_check_boxes :category_ids, Category.where(user_id: current_user.id), :id, :name do |category| %>
        <div class='checkbox'>
          <%= category.check_box%>
          <%= category.label %>
        </div>
      <% end %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
   <% end %>

</section>

app/views/shared/_nav.html.erb
<nav class="nav">
  <div class="hamburger">
    <span class="bar"></span>
    <span class="bar"></span>
    <span class="bar"></span>
  </div>
  <h1 class="categories-h1"><%= h1_content %></h1>
  <ul>
    <li class="nav-link sign-out"><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn-sign-out" %></li>
  </ul>
</nav>

app/views/splash/index.html.erb
<div class='splash'>
    <h1 class='splash_h1'>Budget-App</h1>

    <div id='splash_link'>
        <div>
             <a href="<%= new_user_session_path %>", id='log_in'>LOG IN</a>   
        </div>
       
        <a href="<%= new_user_registration_path %>">SIGN UP</a>
    </div>
</div>

app/views/users/index.html.erb
hi